easy_admin:
#    entities:
        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User


    entities:
        GuestbookPost:
            class: App\Entity\GuestbookPost
            list:
                 fields:
                    ['title', 'body', 'enabled', {  property: 'image', type: 'image', base_path: '%app.path.guestbookpost_images%' }]
            show:
                fields:
                    ['title', 'body', 'enabled',{ property: 'image', type: 'image', base_path: '%app.path.guestbookpost_images%' }]
            form:
                fields:
                    ['title', 'body', 'enabled', { property: 'imageFile', type: 'vich_image' }]

        User:
            class: App\Entity\User
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }

            edit:
                fields:
                    # ...
                    - { property: 'plainPassword', type_options: { required: false} }
                    # ...
                form_options: { validation_groups: ['Profile'] }
            new:
                fields:
                    # ...
                    - { property: 'plainPassword', type_options: { required: true} }
                    # ...
                form_options: { validation_groups: ['Registration'] }

    design:
        assets:
            css:
                # ...
                - 'css/admin.css'



