# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    view:
        view_response_listener:  true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
            - { path: /createClient, prefer_extension: true, fallback_format: json, priorities: [ json ] }
            - { path: '^/admin', stop: true }  # <-- add this line
            - { path: '^/', stop: true }  # <-- add this line
        enabled: true

    body_listener: true

    access_denied_listener:
        json: true


            # ... previous rules declarations

#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }


#    format_listener:
#        enabled: true
#        rules:
#            # ... previous rules declarations
#            - { path: '^/admin', stop: true }  # <-- add this line



#    routing_loader:
#        default_format: json
#        include_format: false
#    body_listener: true
#    format_listener:
#          rules:
#              - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
#    param_fetcher_listener: true
#    access_denied_listener:
#        json: true
#    view:
#        view_response_listener: 'force'
#        formats:
#            json: true